apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::712127117634:role/eksctl-simple-jwt-api1-nodegroup-NodeInstanceRole-11AYLFRIT5J3O
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::698593245670:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2023-01-13T05:45:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1667"
  uid: 73a42133-d511-41fd-9bb6-2ce1647fe005
